name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'PAASON TWO GURIITO'
        default: 'DEFORUTO'
        required: true
        type: string
      is-set-farewell-message:
        description: 'SETTO FARAWERU MESSEEZI'
        required: false
        type: boolean
jobs:
  greet:
    runs-on: ubuntu-latest
    outputs:
      farawell_message: ${{steps.set-farawell-message.outputs.farawell-message}}
    steps:
    - name: SENDO GURIITHINGUS
      run: echo "HAROO ${{inputs.name}}"
    - name: ZYUNBI FARAWERU MESSEEZI
      if: ${{inputs.is-set-farewell-message}}
      id: set-farawell-message
      run: echo "farawell-message=DID YOU RECIEVE THE GREETING I SENT EARLIER?" >> "$GITHUB_OUTPUT"
    - name: DEBAGGU
      if: ${{inputs.is-set-farewell-message}}
      run: echo "${{steps.set-farawell-message.outputs.farawell-message}}"
  faraweru:
    needs: greet
    runs-on: ubuntu-latest
    steps:
    - name: SENDO FARAWERU IFU FURAGU IZU TWORUU
      if: ${{inputs.is-set-farewell-message}}
      run: echo "${{needs.greet.outputs.farawell_message}}"
    - name: SENDO FARAWERU
      if: ${{ inputs.is-set-farewell-message }}
      run: echo "GUDDOBAI ${{inputs.name}}"




