name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'PAASON TWO GURIITO'
        default: 'DEFORUTO'
        required: true
        type: string
      is-set-farewell-message:
        description: 'SETTO FARAWERU MESSEEZI'
        required: false
        type: boolean
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: SENDO GURIITHINGUS
      run: echo "HAROO ${{inputs.name}}"
  faraweru:
    needs: greet
    runs-on: ubuntu-latest
    steps:
    - name: SENDO FARAWERU
      if: ${{ inputs.is-set-farewell-message }}
      run: echo "GUDDOBAI ${{inputs.name}}"
