name: Validate Semantic Versioning
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      version:
        description: 'ENTAA A BAAZYON (TATOEBA v1.0.0)'
        required: true
        type: string
jobs:
  validate-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{steps.set-vars.outputs.tag}}
    steps:
      - name: Set Variables Based on Event
        id: set-vars
        run: |
          tag=""
          if [ "${{ github.event_name }}" == "push" ]; then
            tag=${GITHUB_REF#refs/tags/}
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            tag=${{ inputs.version }}
          else
            echo "Error: Unsupported event_name '${{ github.event_name }}'" >&2
            exit 1
          fi
          echo "tag=${tag}" >> $GITHUB_OUTPUT
          echo "tag=${tag}"

      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Validate Semantic Version (for workflow_dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: ./.github/actions/validate-semver
        with:
          version: ${{ github.event.inputs.version }}
  call-workflow:
    needs: validate-tag
    uses: ./.github/workflows/validation-finished.yaml
    with:
      tag: ${{needs.validate-tag.outputs.tag}}
