name: Validation Finished
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: sstring
jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: Print Tag
        run: echo "TThe tag is ${{inputs.tag}}"
